name: ReleaseAction

on:
  # Lancement manuel
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
    # Compilation du code.
      - name: Compilation du projet
        run: dotnet msbuild /p:Configuration=Release
    # Création de la release
      - name: Création de la release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
