name: ReleaseAction

on:
  # Lancement manuel
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checkout des sources
      - uses: actions/checkout@v2
    # Ces étapes obtiennent la configuration de MSBuild et NuGet et sont ajoutées à la variable PATH
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
    # Compilation du code.
      - name: Build de la solution
        run: msbuild.exe PingOMatic.sln /p:platform="Any CPU" /p:configuration="Release"
    # Création de la release
      - name: Création de la release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Déploiement de la release.
          draft: false
          prerelease: false
