name: ReleaseAction

on:
  # Lancement manuel
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checkout des sources
      - uses: actions/checkout@v2
    # Ces étapes obtiennent la configuration de MSBuild et NuGet et sont ajoutées à la variable PATH
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Restore Packages
        run: nuget restore .\src\PingOMatic\PingOMatic.sln
    # Compilation du code.
      - name: Build de la solution
        run: msbuild.exe .\src\PingOMatic\PingOMatic.sln /p:platform="Any CPU" /p:configuration="Release"
    # Zip de la release
      - name: Zip release
        run: Compress-Archive -Path '.\src\PingOMatic\PingOMatic\bin\Release\*' PingOMatic-Release.zip
    # Création de la release
      - name: Création de la release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: master
          release_name: Release ${{ github.ref }}
          body: |
            Déploiement de la release.
          draft: false
          prerelease: false
      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: PingOMatic-Release.zip
          asset_name: PingOMatic-Release.zip
          asset_content_type: application/zip
